// GENERAL
export const ERROR = 'ERROR'
export const STORE_UPDATED = 'STORE_UPDATED'
export const TX_SUBMITTED = 'TX_SUBMITTED'

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'
export const CONNECT_WALLET = 'CONNECT_WALLET'

export const CONFIGURE = 'CONFIGURE'
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED'

export const ACCOUNT_CONFIGURED = 'ACCOUNT_CONFIGURED'
export const ACCOUNT_CHANGED = 'ACCOUNT_CHANGED'

export const GET_GAS_PRICES = 'GET_GAS_PRICES'
export const GAS_PRICES_RETURNED = 'GAS_PRICES_RETURNED'

// STABLE SWAP
export const UPDATED = 'UPDATED'

export const CONFIGURE_SS = 'CONFIGURE_SS'
export const CONFIGURED_SS = 'CONFIGURED_SS'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const SEARCH_ASSET = 'SEARCH_ASSET'
export const ASSET_SEARCHED = 'ASSET_SEARCHED'

export const CREATE_PAIR = 'CREATE_PAIR'
export const PAIR_CREATED = 'PAIR_CREATED'

export const APPROVE_ADD_LIQUIDITY = 'APPROVE_ADD_LIQUIDITY'
export const ADD_LIQUIDITY_APPROVED = 'ADD_LIQUIDITY_APPROVED'

export const ADD_LIQUIDITY = 'ADD_LIQUIDITY'
export const LIQUIDITY_ADDED = 'LIQUIDITY_ADDED'

export const QUOTE_ADD_LIQUIDITY = 'QUOTE_ADD_LIQUIDITY'
export const QUOTE_ADD_LIQUIDITY_RETURNED = 'QUOTE_ADD_LIQUIDITY_RETURNED'

export const GET_ADD_LIQUIDITY_ALLOWANCE = 'GET_ADD_LIQUIDITY_ALLOWANCE'
export const GET_ADD_LIQUIDITY_ALLOWANCE_RETURNED = 'GET_ADD_LIQUIDITY_ALLOWANCE_RETURNED'
